name: Release PDF

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build PDF
      uses: justforlxz/deepin-builder-docker/latex@master
      with:
        file: ./deepin-styleguide.tex
    - name: Upload PDF to release artifacts
      uses: softprops/action-gh-release@v1
      with:
        files: deepin-styleguide.pdf
